[package]
distribution = "2201.10.0"
org = "ballerinax"
name = "hubspot.crm.obj.contacts"
version = "@toml.version@"
license = ["Apache-2.0"]
authors = ["Ballerina"]
keywords = ["hubspot", "customer", "management", "connector", "crm"]
repository = "https://github.com/ballerina-platform/module-ballerinax-hubspot.crm.obj.contacts"

[build-options]
observabilityIncluded = true

[platform.java17]
graalvmCompatible = true
